# language: objective-c
# osx_image: xcode8
# script:
#     - set -o pipefail
#     - bundle exec fastlane push
language: swift
osx_image: xcode10.1
cache:
  bundler: true

branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/  

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=DangerPOC.xcodeproj
    - SCHEME="DangerPOC"

  matrix:
    - DESTINATION="OS=12.1,name=iPhone XR"                   

before_install: 
  - gem install bundler
  - gem install xcpretty  slather -N
  - rvm use $RVM_RUBY_VERSION

install: 
  - bundle install --without=documentation --path ../travis_bundle_dir
  - gem install slather --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty -N
  - gem install coveralls

jobs:
  include:
    - stage: Clean-Build
      script: 
        # - xcodebuild clean build-for-testing -project DangerPOC.xcodeproj -scheme "DangerPOC" -destination "name=iPhone XR,OS=12.1"
        - set -o pipefail && xcodebuild -project DangerPOC.xcodeproj -scheme "DangerPOC" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' -enableCodeCoverage YES clean build-for-testing test | xcpretty -r "html" -o "Report/build.html"

    # - stage: Tests
    #   script: 
    #     # - xcodebuild clean test -project DangerPOC.xcodeproj -scheme "DangerPOC" -destination "name=iPhone XR,OS=12.1"
    #     - set -o pipefail && xcodebuild -project DangerPOC.xcodeproj -scheme "DangerPOC" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' test | xcpretty -r "html" -o "Report/tests.html"

    # - stage: Coverage
    #   script: 
    #     - slather
    #     - slather coverage -s --scheme DangerPOC DangerPOC.xcodeproj
    #     - slather coverage --html --output-directory Report/slather --scheme DangerPOC  DangerPOC.xcodeproj
# script:  
#   - xcodebuild build-for-testing -project TwitchApp.xcodeproj -scheme TwitchApp -destination "name=iPhone X,OS=12.1"
#   - xcodebuild clean test -project TwitchApp.xcodeproj -scheme "TwitchApp" -destination "name=iPhone X,OS=12.1"

notifications:
  email:
    on_success: never

after_success: 
  - slather
  - slather coverage --show --html --output-directory Report/slather --scheme DangerPOC  DangerPOC.xcodeproj
  - slather coverage --html --output-directory Report/slather --scheme DangerPOC  DangerPOC.xcodeproj
  - coveralls push
  # - coveralls push
  # - bundle exec slather
  # - slather coverage -s --scheme DangerPOC DangerPOC.xcodeproj
  # - slather coverage --html --output-directory Report/slather --scheme DangerPOC  DangerPOC.xcodeproj
  # - slather #Coveralls
  # - bash <(curl -s https://codecov.io/bash) -J 'DangerPOC #Codecov
  # - bash <(curl -s https://codecov.io/bash) -f path/to/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode #Codecov


# language: objective-c
# before_install:
#   - sudo easy_install cpp-coveralls
#   - brew uninstall xctool
#   - brew update
#   - brew install xctool --HEAD  
# script:
#   - xctool test ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
# after_success:
#   - ./script/coveralls.sh





  