language: swift
osx_image: xcode10.1
cache:
  bundler: true

branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/  

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=DangerPOC.xcodeproj
    - SCHEME="DangerPOC"

  matrix:
    - DESTINATION="OS=12.1,name=iPhone XR"                   

before_install: 
  - gem install bundler

install: 
  - bundle install
  - gem install slather -N #gem install slather --no-ri --no-rdoc  gem install slather --no-rdoc --no-ri --no-document --quiet
  - gem install danger
  - gem install coveralls
  - gem install slather
  - gem install xcpretty
  - gem install xcov
  - gem install danger-xcov
  - gem install danger-commit_lint

jobs:
  include:
    - stage: Clean-Build-Tests
      script: 
        - bash Script/run-test.sh

after_success: 
  - slather coverage -x --output-directory Report/slather/xml_report --scheme DangerPOC  DangerPOC.xcodeproj
  - bash <(curl -s https://codecov.io/bash) -f Report/slather/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
  # - slather
  # - bash Script/coveralls.sh 

notifications:
  email: never
    # on_success: never





  