language: swift
osx_image: xcode10.1
cache:
  bundler: true

branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/  

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=DangerPOC.xcodeproj
    - SCHEME="DangerPOC"

  matrix:
    - DESTINATION="OS=12.1,name=iPhone XR"                   

before_install: 
  - gem install bundler

install: bundle install

jobs:
  include:
    - stage: Clean-Build-Tests
      script: 
        - echo "*** Start Clean Build Tests *** "
        - set -o pipefail && xcodebuild -project DangerPOC.xcodeproj -scheme DangerPOC -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' -enableCodeCoverage YES clean build-for-testing test | xcpretty -r "html" -o "Report/build.html"
        - echo "*** Finish Clean Build Tests *** "
after_success: 
  - bash Script/coveralls.sh
  - slather    

notifications:
  email:
    on_success: never





  