# Coveralls
coverage_service: coveralls
xcodeproj: DangerPOC/DangerPOC.xcodeproj
scheme: DangerPOC
ignore:
  - DangerPOCTests/*

# Codecov

# coverage_service: cobertura_xml
# xcodeproj: DangerPOC/DangerPOC.xcodeproj
# scheme: DangerPOC
# source_directory: DangerPOC/
# output_directory: Coverage/xml_report
# ignore:
#   - DangerPOCTests/*

# Cobertura

# coverage_service: cobertura_xml
# xcodeproj: DangerPOC/DangerPOC.xcodeproj
# scheme: DangerPOC
# source_directory: DangerPOC/
# output_directory: Coverage/xml_report
# ignore:
#   - DangerPOCTests/*

# slather coverage -x --output-directory path/to/xml_report

# Static HTML

# slather coverage --html --scheme YourXcodeSchemeName path/to/project.xcodeproj